### ISSUE TITLE
HTTP 404 error

### ISSUE THREAD

**Issue by MSCTR** [b2slab/FELLA#15]
Hi,
I have been trying to run the code you have provided in one of your vignettes but I keep getting the following error:

**Error in .getUrl(url, .listParser, nameColumn = 1, valueColumn = 2) :  Not Found (HTTP 404).**

The code I used for the same is:
_library(KEGGREST)
library(igraph)
library(magrittr)
set.seed(1)
graph <- buildGraphFromKEGGREST(organism = "mmu", filter.path = c("01100", "01200", "01210", "01212", "01230"))_

Is this an error from the KEGG database end or the Bioconductor end?

**Comment by SergiPicart** [comment]
Hi, this was already [reported](https://support.bioconductor.org/p/125268/) and a fix was issued.

If you use the latest `FELLA` version in [Bioc release](http://bioconductor.org/packages/release/bioc/html/FELLA.html) it should work as usual.

Best,
Sergi

**Comment by SergiPicart** [comment]
I believe this is solved, tell me otherwise. Closing
