### ISSUE TITLE
how to correct for multiple testing with p.scores using diffusion method

### ISSUE THREAD

**Issue by mingwhy** [b2slab/FELLA#19]
Hello,

Thank you for this amazing tool!

I'm using your R package 'FELLA' to perform pathway enrichment analysis.
I have a question for the p scores generated using the function `runDiffusion`.
I saw there is a p.score for each pathway, module, enzyme, reaction, and compound. In my case, my metabolome data was generated from fruit flies, there are 10558 pathway/module/enzyme/reaction/compound items, or p.scores.

I guess the p score is analogous to p value? There were 740 p.scores smaller than 0.05.
Then if I apply multiple-testing correction using the p.adjust() function in R, none of the corrected 10558 p.scores was smaller than 0.05.

I wonder if I understand the p.score correctly, and do you have any suggestions for multiple-testing correction on those p scores?
Thank you so much!
All the best!
Ming

**Comment by SergiPicart** [comment]
Dear Ming, 
The short answer is FELLA's p.scores are not corrected for multiple testing and not used as p-values, but as a statistically adjusted prioritiser. Please find a more detailed discussion on this topic in the Bioc forum: https://support.bioconductor.org/p/9140352

Thank you for your interest in FELLA!
